services:
  api:
    container_name: api
    build: .
    ports:
      - "8080:8080"
    links:
      - db
  db:
    container_name: db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nba
    volumes:
      - db_volume:/db/
volumes:
  db_volume:
