name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v3.0.3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Checkout code
        uses: actions/checkout@v3.0.2
      - name: Set up JDK 17
        uses: actions/setup-java@v3.3.0
        with:
          java-version: "17"
          distribution: "temurin"
      - name: Lint Code Base
        uses: github/super-linter@v4.9.4
      - name: GitHub Actions Workflow Linter
        uses: cschleiden/actions-linter@v1
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.1.7
        with:
          arguments: build
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: SonarQube Quality Gate Check
        uses: SonarSource/sonarqube-quality-gate-action@v1.0.0
      - name: Official SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v1.1.0
      - name: Container image scan
        uses: Azure/container-scan@v0.1
